version: '3'

services:

  kafka13:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka13
    ports:
      - "9104:9104"
    environment:
      KAFKA_BROKER_ID: 13
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka13:29104,PLAINTEXT_HOST://192.168.0.108:9104
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka14:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka14
    ports:
      - "9105:9105"
    environment:
      KAFKA_BROKER_ID: 14
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka14:29105,PLAINTEXT_HOST://192.168.0.108:9105
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka15:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka15
    ports:
      - "9106:9106"
    environment:
      KAFKA_BROKER_ID: 15
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka15:29106,PLAINTEXT_HOST://192.168.0.108:9106
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka16:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka16
    ports:
      - "9107:9107"
    environment:
      KAFKA_BROKER_ID: 16
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka16:29107,PLAINTEXT_HOST://192.168.0.108:9107
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka17:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka17
    ports:
      - "9108:9108"
    environment:
      KAFKA_BROKER_ID: 17
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka17:29108,PLAINTEXT_HOST://192.168.0.108:9108
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka18:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka18
    ports:
      - "9109:9109"
    environment:
      KAFKA_BROKER_ID: 18
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka18:29109,PLAINTEXT_HOST://192.168.0.108:9109
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka19:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka19
    ports:
      - "9110:9110"
    environment:
      KAFKA_BROKER_ID: 19
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka19:29110,PLAINTEXT_HOST://192.168.0.108:9110
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka20:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka20
    ports:
      - "9111:9111"
    environment:
      KAFKA_BROKER_ID: 20
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka20:29111,PLAINTEXT_HOST://192.168.0.108:9111
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka21:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka21
    ports:
      - "9112:9112"
    environment:
      KAFKA_BROKER_ID: 21
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka21:29112,PLAINTEXT_HOST://192.168.0.108:9112
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka22:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka22
    ports:
      - "9113:9113"
    environment:
      KAFKA_BROKER_ID: 22
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka22:29113,PLAINTEXT_HOST://192.168.0.108:9113
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka23:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka23
    ports:
      - "9114:9114"
    environment:
      KAFKA_BROKER_ID: 23
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka23:29114,PLAINTEXT_HOST://192.168.0.108:9114
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka24:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka24
    ports:
      - "9115:9115"
    environment:
      KAFKA_BROKER_ID: 24
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.106:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka24:29115,PLAINTEXT_HOST://192.168.0.108:9115
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1